{"uuid":"8d9b66e8-fa93-4a70-bb81-9200421d281a","historyId":"c596847c8fd0d762232eeb3e1c2e3eef","fullName":"testcases.testfordocker.dockerTestCase5","labels":[{"name":"package","value":"testcases.testfordocker"},{"name":"testClass","value":"testcases.testfordocker"},{"name":"testMethod","value":"dockerTestCase5"},{"name":"parentSuite","value":"All Test Suite"},{"name":"suite","value":"C:\\Users\\abdel\\Desktop\\mayssapfe\\PFE-ALM-TestAutomation-main\\TestAutomation-main\\PFE"},{"name":"subSuite","value":"testcases.testfordocker"},{"name":"host","value":"LAPTOP-VBGTRF9D"},{"name":"thread","value":"12512@LAPTOP-VBGTRF9D.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"epic","value":"testfordocker tests"},{"name":"feature","value":"testfordocker Tests"}],"links":[],"name":"dockerTestCase5","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [https://www.google.com/] but found [https://www.googgle.com//]","trace":"java.lang.AssertionError: expected [https://www.google.com/] but found [https://www.googgle.com//]\r\n\tat org.testng.Assert.fail(Assert.java:99)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:1037)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:140)\r\n\tat org.testng.Assert.assertEquals(Assert.java:122)\r\n\tat org.testng.Assert.assertEquals(Assert.java:629)\r\n\tat org.testng.Assert.assertEquals(Assert.java:639)\r\n\tat testcases.testfordocker.dockerTestCase5(testfordocker.java:74)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:577)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)\r\n\tat org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)\r\n\tat org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)\r\n\tat org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)\r\n\tat org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)\r\n\tat java.base/java.util.ArrayList.forEach(ArrayList.java:1511)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:764)\r\n\tat org.testng.TestRunner.run(TestRunner.java:585)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:384)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:286)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1140)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1069)\r\n\tat org.testng.TestNG.run(TestNG.java:1037)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)\r\n"},"stage":"finished","description":"Docker Test Case 5","steps":[],"attachments":[{"name":"Page Screenshot","source":"28d84178-0c65-41e3-aa7a-f654f71a2922-attachment","type":"image/png"},{"name":"dockerTestCase5 failed and screenshot taken","source":"9675bf0e-648f-41b3-b639-6af5e4f0f655-attachment","type":"text/plain"}],"parameters":[],"start":1712578968340,"stop":1712578969608}